import { promises as fs } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { PrdJson, QuestionsForClient } from "../models/schema.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export interface PrdGeneratorOptions {
  outputDir: string;
  projectName: string;
  templatePath?: string;
}

/**
 * Writes PRD artifacts (JSON files and Markdown PRD) to the output directory
 * @param prd - Complete PRD JSON structure
 * @param questions - Questions for client
 * @param options - Options including output directory and project name
 */
export async function writePrdArtifacts(
  prd: PrdJson,
  questions: QuestionsForClient,
  options: PrdGeneratorOptions
): Promise<void> {
  // Ensure output directory exists
  try {
    await fs.mkdir(options.outputDir, { recursive: true });
  } catch (error) {
    throw new Error(
      `Failed to create output directory: ${error instanceof Error ? error.message : String(error)}`
    );
  }

  // Write prd-structured.json
  const prdJsonPath = path.join(options.outputDir, "prd-structured.json");
  try {
    await fs.writeFile(prdJsonPath, JSON.stringify(prd, null, 2), "utf-8");
  } catch (error) {
    throw new Error(
      `Failed to write PRD JSON: ${error instanceof Error ? error.message : String(error)}`
    );
  }

  // Write questions-for-client.json
  const questionsPath = path.join(options.outputDir, "questions-for-client.json");
  try {
    await fs.writeFile(questionsPath, JSON.stringify(questions, null, 2), "utf-8");
  } catch (error) {
    throw new Error(
      `Failed to write questions JSON: ${error instanceof Error ? error.message : String(error)}`
    );
  }

  // Generate Markdown PRD
  const sanitizedProjectName = options.projectName
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
  const markdownPath = path.join(options.outputDir, `PRD_${sanitizedProjectName}.md`);

  let markdownContent: string;

  // Resolve template path
  const templatePath =
    options.templatePath ||
    path.resolve(process.cwd(), "templates", "PRD_Template.md");

  // Try to read template
  try {
    const templateContent = await fs.readFile(templatePath, "utf-8");

    // Replace {{projectName}} placeholder
    const projectName = prd.tier1?.projectName || options.projectName;
    markdownContent = templateContent.replace(/\{\{projectName\}\}/g, projectName);

    // Append JSON snapshot section
    markdownContent += `\n\n## JSON Snapshot\n\n\`\`\`json\n${JSON.stringify(prd, null, 2)}\n\`\`\`\n`;
  } catch (error) {
    // Template not found or unreadable, generate fallback Markdown
    const projectName = prd.tier1?.projectName || options.projectName;
    markdownContent = `# Product Requirements Document: ${projectName}\n\n`;
    markdownContent += `*Generated by Product Intelligence Engine*\n\n`;
    markdownContent += `## Overview\n\n`;
    markdownContent += `This PRD was automatically generated from repository code analysis.\n\n`;
    markdownContent += `## JSON Snapshot\n\n`;
    markdownContent += `\`\`\`json\n${JSON.stringify(prd, null, 2)}\n\`\`\`\n`;
  }

  // Write Markdown file
  try {
    await fs.writeFile(markdownPath, markdownContent, "utf-8");
  } catch (error) {
    throw new Error(
      `Failed to write PRD Markdown: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}
